import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FAlertStyles alertStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primary = FAlertStyle(
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.md.fontSize,
    ),
    titleTextStyle: typography.display.sm.copyWith(
      fontWeight: .w500,
      color: colors.foreground,
    ),
    subtitleTextStyle: (touch ? typography.body.xs : typography.body.sm)
        .copyWith(color: colors.mutedForeground),
    decoration: ShapeDecoration(
      shape: RoundedSuperellipseBorder(
        side: BorderSide(color: colors.border, width: style.borderWidth),
        borderRadius: style.borderRadius.md,
      ),
      color: colors.card,
    ),
  );
  return FAlertStyles(
    FVariants.from(
      primary,
      variants: {
        [.primary]: const .delta(),
        [.destructive]: .delta(
          iconStyle: .delta(color: colors.destructive),
          titleTextStyle: .delta(color: colors.destructive),
          subtitleTextStyle: .delta(color: colors.destructive),
        ),
      },
    ),
  );
}
