import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.color,
///  style: FThemes.neutral.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.color,
///    style: FThemes.neutral.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FVariants<FBadgeVariantConstraint, FBadgeVariant, FBadgeStyle, FBadgeStyleDelta>
badgeStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FVariants.from(
  FBadgeStyle(
    
    decoration: BoxDecoration(
      color: colors.primary,
      borderRadius: FBadgeStyles.defaultBadgeRadius,
    ),
    contentStyle: FBadgeContentStyle(
      padding: .symmetric(horizontal: 12, vertical: 6),
      labelTextStyle: typography.sm.copyWith(
        color: colors.primaryForeground,
        fontWeight: .w600,
      ),
    ),
  ),
  variants: {
    [.secondary]: .delta(
      decoration: .delta(color: colors.secondary),
      contentStyle: .delta(
        padding: .symmetric(horizontal: 12, vertical: 6),
        labelTextStyle: .delta(color: colors.secondaryForeground),
      ),
    ),
    [.destructive]: FBadgeStyle(
      decoration: BoxDecoration(
        borderRadius: FBadgeStyles.defaultBadgeRadius,
        color: colors.destructive.withValues(
          alpha: colors.brightness == .light ? 0.1 : 0.2,
        ),
      ),
      contentStyle: FBadgeContentStyle(
        padding: .symmetric(horizontal: 12, vertical: 6),
        labelTextStyle: typography.sm.copyWith(
          color: colors.destructive,
          fontWeight: .w600,
        ),
      ),
    ),
    [.outline]: .delta(
      decoration: .delta(
        color: colors.card,
        border: .all(color: colors.border, width: style.borderWidth),
      ),
      contentStyle: .delta(
        padding: .symmetric(horizontal: 12, vertical: 6),
        labelTextStyle: .delta(color: colors.foreground)),
    ),
  },
);
