import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.color,
///  style: FThemes.neutral.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.color,
///    style: FThemes.neutral.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FVariants<
  FButtonVariantConstraint,
  FButtonVariant,
  FButtonSizes,
  FButtonSizesDelta
>
buttonStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FVariants(
  _buttonSizeStyles(
    typography: typography,
    style: style,
    decoration: FVariants.from(
      BoxDecoration(borderRadius: style.borderRadius, color: colors.primary),
      variants: {
        [.hovered, .pressed]: .delta(color: colors.hover(colors.primary)),
        [.disabled]: .delta(color: colors.disable(colors.primary)),
        [.selected]: .delta(color: colors.hover(colors.primary)),
        [.selected.and(.disabled)]: .delta(
          color: colors.disable(colors.hover(colors.primary)),
        ),
      },
    ),
    foregroundColor: colors.primaryForeground,
    disabledForegroundColor: colors.disable(colors.primaryForeground),
  ),
  variants: {
    [.secondary]: _buttonSizeStyles(
      typography: typography,
      style: style,
      decoration: FVariants.from(
        BoxDecoration(
          borderRadius: style.borderRadius,
          color: colors.secondary,
        ),
        variants: {
          [.hovered, .pressed]: .delta(color: colors.hover(colors.secondary)),
          [.disabled]: .delta(color: colors.disable(colors.secondary)),
          [.selected]: .delta(color: colors.hover(colors.secondary)),
          [.selected.and(.disabled)]: .delta(
            color: colors.disable(colors.hover(colors.secondary)),
          ),
        },
      ),
      foregroundColor: colors.secondaryForeground,
      disabledForegroundColor: colors.disable(colors.secondaryForeground),
    ),
    [.destructive]: _buttonSizeStyles(
      typography: typography,
      style: style,
      decoration: FVariants.from(
        BoxDecoration(
          borderRadius: style.borderRadius,
          color: colors.destructive.withValues(
            alpha: colors.brightness == .light ? 0.1 : 0.2,
          ),
        ),
        variants: {
          [.hovered, .pressed]: .delta(
            color: colors.destructive.withValues(
              alpha: colors.brightness == .light ? 0.2 : 0.3,
            ),
          ),
          [.disabled]: .delta(
            color: colors.destructive.withValues(
              alpha: colors.brightness == .light ? 0.05 : 0.1,
            ),
          ),
          [.selected]: .delta(
            color: colors.destructive.withValues(
              alpha: colors.brightness == .light ? 0.2 : 0.3,
            ),
          ),
          [.selected.and(.disabled)]: .delta(
            color: colors.disable(
              colors.destructive.withValues(
                alpha: colors.brightness == .light ? 0.2 : 0.3,
              ),
            ),
          ),
        },
      ),
      foregroundColor: colors.destructive,
      disabledForegroundColor: colors.destructive.withValues(alpha: 0.5),
    ),
    [.outline]: _buttonSizeStyles(
      typography: typography,
      style: style,
      decoration: FVariants.from(
        BoxDecoration(
          border: .all(color: colors.border),
          borderRadius: style.borderRadius,
          color: colors.card,
        ),
        variants: {
          [.hovered, .pressed]: .delta(color: colors.secondary),
          [.disabled]: .delta(color: colors.disable(colors.card)),
          [.selected]: .delta(color: colors.secondary),
          [.selected.and(.disabled)]: .delta(
            color: colors.disable(colors.secondary),
          ),
        },
      ),
      foregroundColor: colors.secondaryForeground,
      disabledForegroundColor: colors.disable(colors.secondaryForeground),
    ),
    [.ghost]: _buttonSizeStyles(
      typography: typography,
      style: style,
      decoration: FVariants.from(
        BoxDecoration(borderRadius: style.borderRadius),
        variants: {
          [.hovered, .pressed]: .delta(color: colors.secondary),
          [.disabled]: const .delta(),
          [.selected]: .delta(color: colors.secondary),
          [.selected.and(.disabled)]: .delta(
            color: colors.disable(colors.secondary),
          ),
        },
      ),
      foregroundColor: colors.secondaryForeground,
      disabledForegroundColor: colors.disable(colors.secondaryForeground),
    ),
  },
);

FVariants<
  FButtonSizeVariantConstraint,
  FButtonSizeVariant,
  FButtonStyle,
  FButtonStyleDelta
>
_buttonSizeStyles({
  required FTypography typography,
  required FStyle style,
  required FVariants<
    FTappableVariantConstraint,
    FTappableVariant,
    BoxDecoration,
    BoxDecorationDelta
  >
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
}) {
  FButtonStyle button({
    required TextStyle textStyle,
    required EdgeInsetsGeometry contentPadding,
    required double contentSpacing,
    required double iconSize,
    required EdgeInsetsGeometry iconPadding,
  }) => FButtonStyle(
    decoration: decoration,
    focusedOutlineStyle: style.focusedOutlineStyle,
    contentStyle: FButtonContentStyle(
      textStyle: FVariants.from(
        textStyle.copyWith(
          color: foregroundColor,
          fontWeight: .w500,
          height: 1,
          leadingDistribution: .even,
        ),
        variants: {
          [.disabled]: .delta(color: disabledForegroundColor),
        },
      ),
      iconStyle: FVariants.from(
        IconThemeData(color: foregroundColor, size: iconSize),
        variants: {
          [.disabled]: .delta(color: disabledForegroundColor),
        },
      ),
      circularProgressStyle: FVariants.from(
        FCircularProgressStyle(
          iconStyle: IconThemeData(color: foregroundColor, size: iconSize),
        ),
        variants: {
          [.disabled]: .delta(
            iconStyle: .delta(color: disabledForegroundColor),
          ),
        },
      ),
      padding: contentPadding,
      spacing: contentSpacing,
    ),
    iconContentStyle: FButtonIconContentStyle(
      iconStyle: FVariants.from(
        IconThemeData(color: foregroundColor, size: iconSize),
        variants: {
          [.disabled]: .delta(color: disabledForegroundColor),
        },
      ),
      padding: iconPadding,
    ),
    tappableStyle: style.tappableStyle,
  );
  return FVariants(
    button(
      textStyle: typography.base,
      contentPadding: const .symmetric(horizontal: 16, vertical: 11),
      contentSpacing: 10,
      iconSize: typography.base.fontSize ?? 16,
      iconPadding: const .all(11),
    ),
    variants: {
      [.xs]: button(
        textStyle: typography.xs,
        contentPadding: const .symmetric(horizontal: 8, vertical: 7),
        contentSpacing: 6,
        iconSize: typography.xs.fontSize ?? 12,
        iconPadding: const .all(7),
      ),
      [.sm]: button(
        textStyle: typography.sm,
        contentPadding: const .symmetric(horizontal: 12, vertical: 9),
        contentSpacing: 8,
        iconSize: typography.sm.fontSize ?? 14,
        iconPadding: const .all(9),
      ),
      [.lg]: button(
        textStyle: typography.base,
        contentPadding: const .symmetric(horizontal: 32, vertical: 14),
        contentSpacing: 10,
        iconSize: typography.base.fontSize ?? 16,
        iconPadding: const .all(14),
      ),
    },
  );
}
