import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FCardStyle cardStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  TextStyle titleTextStyle;
  double titleSpacing;
  double subtitleSpacing;
  if (touch) {
    titleTextStyle = typography.display.lg.copyWith(
      fontWeight: .w500,
      color: colors.foreground,
    );
    titleSpacing = 4;
    subtitleSpacing = 8;
  } else {
    titleTextStyle = typography.display.md.copyWith(
      fontWeight: .w500,
      color: colors.foreground,
    );
    titleSpacing = 2;
    subtitleSpacing = 6;
  }
  return FCardStyle(
    decoration: ShapeDecoration(
      shape: RoundedSuperellipseBorder(
        side: BorderSide(color: colors.border, width: style.borderWidth),
        borderRadius: style.borderRadius.lg,
      ),
      color: colors.card,
    ),
    contentStyle: FCardContentStyle(
      titleTextStyle: titleTextStyle,
      subtitleTextStyle: typography.body.sm.copyWith(
        color: colors.mutedForeground,
      ),
      titleSpacing: titleSpacing,
      subtitleSpacing: subtitleSpacing,
    ),
  );
}
