import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FCircularProgressSizeStyles circularProgressSizeStyles({
  required FColors colors,
  required FTypography typography,
}) {
  final md = _circularProgressStyle(
    colors: colors,
    iconSize: typography.body.md.fontSize!,
  );
  return FCircularProgressSizeStyles(
    FVariants(
      md,
      variants: {
        [.xs]: _circularProgressStyle(
          colors: colors,
          iconSize: typography.body.xs.fontSize!,
        ),
        [.sm]: _circularProgressStyle(
          colors: colors,
          iconSize: typography.body.sm.fontSize!,
        ),
        [.md]: md,
        [.lg]: _circularProgressStyle(
          colors: colors,
          iconSize: typography.body.lg.fontSize!,
        ),
        [.xl]: _circularProgressStyle(
          colors: colors,
          iconSize: typography.body.xl.fontSize!,
        ),
      },
    ),
  );
}

FCircularProgressStyle _circularProgressStyle({
  required FColors colors,
  double iconSize = 20,
}) => FCircularProgressStyle(
  iconStyle: IconThemeData(color: colors.mutedForeground, size: iconSize),
  motion: const FCircularProgressMotion(),
);
