part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
    systemOverlayStyle: .dark,
    barrier: Color.fromARGB(255, 109, 40, 217),
    background: Color.fromARGB(255, 250, 250, 250),
    foreground: Color.fromARGB(255, 23, 26, 33),
    primary: Color.fromARGB(255, 16, 185, 129),
    primaryForeground: Color.fromARGB(255, 0, 0, 0),
    secondary: Color.fromARGB(255, 7, 133, 236),
    secondaryForeground: Color.fromARGB(255, 255, 255, 255),
    muted: Color(0xFFF4F4F5),
    mutedForeground: Color(0xFF71717A),
    destructive: Color.fromARGB(255, 242, 92 , 77),
    destructiveForeground: Color(0xFFFAFAFA),
    error: Color(0xFFEF4444),
    errorForeground: Color(0xFFFAFAFA),
    border: Color(0xFFE4E4E7),
    card: Color.fromARGB(255, 250, 250, 250),
    extensions: const [AppColors(
      success: Color.fromARGB(255, 16, 185, 129),
      accent: Color.fromARGB(255, 0, 0, 0),
      white: Colors.white

    )],
);

final FColors darkColors = FColors(
    brightness: .dark,
    systemOverlayStyle: .light,
    barrier: Color.fromARGB(255, 109, 40, 217),
    background: Color(0xFF09090B),
    foreground: Color.fromARGB(255, 23, 26, 33),
    primary: Color.fromARGB(255, 16, 185, 129),
    primaryForeground: Color.fromARGB(255, 255, 255, 255),
    secondary: Color.fromARGB(255, 7, 133, 236),
    secondaryForeground: Color.fromARGB(255, 24, 32, 46),
    muted: Color(0xFF27272A),
    mutedForeground: Color(0xFFA1A1AA),
    destructive: Color.fromARGB(255, 242, 92 , 77),
    destructiveForeground: Color(0xFFFAFAFA),
    error: Color(0xFF7F1D1D),
    
    errorForeground: Color(0xFFFAFAFA),
    border: Color(0xFF27272A),
    card: Color.fromARGB(255, 0, 0, 0),
    extensions: const [AppColors(
      success: Color.fromARGB(255, 16, 185, 129),
      accent: Color.fromARGB(255, 0, 0, 0),
      white: Colors.white

    )],
).copyWith();

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.
class AppColors extends ThemeExtension<AppColors> {
  // TODO: add your color fields here:
  // final Color accent;
  final Color accent;
  final Color success;
  final Color white;

  const AppColors({
    required this.accent,
    required this.success,
    required this.white,
  });

  @override
  AppColors copyWith({Color? accent, Color? success}) {
    return AppColors(
      white: white ?? this.white,
      accent: accent ?? this.accent,
      success: success ?? this.success,
    );
  }

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) return this;
    return AppColors(
      white: Color.lerp(white, other.white, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      success: Color.lerp(success, other.success, t)!,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
