import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';
import 'package:path/path.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.color,
///  style: FThemes.neutral.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.color,
///    style: FThemes.neutral.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FDateFieldStyle dateFieldStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FDateFieldStyle(
  
  // fieldStyle: .inherit(colors: colors, typography: typography, style: style),
  fieldStyle: .new(
    keyboardAppearance: Brightness.light,
    // Input body color 
    color: .all(colors.secondaryForeground.withValues(alpha: 0.3)), 
    iconStyle: .all(.new( color: colors.primaryForeground)), 
    clearButtonStyle:
    
    .new(
      decoration: .all(BoxDecoration(
        color: colors.primary
      )), 
      contentStyle: .new(
        textStyle: .all(.new()), 
        iconStyle: .all(.new()), 
        circularProgressStyle: .all(.new(iconStyle: .new()))), 
      iconContentStyle: .new(iconStyle: .all(.new())), 
      tappableStyle: .new(), 
      focusedOutlineStyle: .new(color: colors.background, borderRadius: .zero)
    ), 
    obscureButtonStyle: .new(
      decoration: .all(.new()), 
      contentStyle: .new(
        textStyle: .all(.new()), 
        iconStyle: .all(.new()), 
        circularProgressStyle: .all(.new(iconStyle: .new()))), 
      iconContentStyle: .new(iconStyle: .all(.new())), 
      tappableStyle: .new(), 
      focusedOutlineStyle: .new(color: colors.background, borderRadius: .zero)
    ),
    // active date style 
    contentTextStyle: .all(.new(color: colors.primaryForeground)), 
    // placeholder text 
    hintTextStyle: .all(.new( color: colors.primaryForeground)), 
    counterTextStyle: .all(.new()), 
    border: .all(.none), 
    labelTextStyle: .all(.new(color: colors.primaryForeground)), 
    descriptionTextStyle: .all(.new( color: colors.primaryForeground, )), 
    errorTextStyle: .all(.new())
    ),
    popoverStyle: FPopoverStyle(decoration: BoxDecoration()),
  calendarStyle: .new(
    yearMonthPickerStyle: .new(
      //set
      backgroundColor: .all(colors.secondaryForeground.withValues(alpha: .1)), 
      borderColor: .all(colors.primaryForeground.withValues(alpha: .05)), 
      textStyle: .all(.new()), 
      radius: .zero
    ),
      headerStyle: .new(
        focusedOutlineStyle: .new(
          color: colors.destructive, 
          borderRadius: .zero
          ), 
        buttonStyle: .new(
          // set
          decoration: .all(.new(color: colors.primary.withValues(alpha: .1))), 
          contentStyle: .new(
            textStyle: .all(.new()), 
            iconStyle: .all(.new(color: colors.destructive)), 
            circularProgressStyle: .all(.new(iconStyle: .new()))), 
            // HEADER ICON STYLE
          iconContentStyle: .new(iconStyle: .all(.new( color: colors.primaryForeground))), 
          tappableStyle: .new(), 
          focusedOutlineStyle: .new(color: colors.background, borderRadius: .zero)
        ), 
        headerTextStyle: .new()
      ),
      dayPickerStyle: FCalendarDayPickerStyle(
        headerTextStyle: .new(), 
        current: .new(
          // set
          backgroundColor: .all(colors.secondaryForeground.withValues(alpha: .1)), 
          borderColor: .all(colors.primaryForeground.withValues(alpha: .05)), 
          // set
          textStyle: .all(.new( color: colors.primaryForeground)), 
          radius: .zero), 
        enclosing: .new(
          //set
          backgroundColor: .all(colors.secondaryForeground.withValues(alpha: .1)), 
          borderColor: .all(colors.primaryForeground.withValues(alpha: .05)), 
          // set
          textStyle: .all( .new(color: colors.primaryForeground.withValues(alpha: .5))), 
          radius: .zero
        )
      ),

      // POP UP
    decoration: BoxDecoration( color: colors.secondaryForeground 
    )
    )
);
