import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FDateFieldStyle dateFieldStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required FHapticFeedback hapticFeedback,
  required bool touch,
}) => FDateFieldStyle(
  fieldStyles: .inherit(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ),
  popoverStyle: .inherit(colors: colors, style: style),
  calendarStyle: .inherit(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    hapticFeedback: hapticFeedback,
    touch: touch,
  ),
).copyWith(
  fieldStyles: FVariantsDelta<
    FTextFieldSizeVariantConstraint,
    FTextFieldSizeVariant,
    FTextFieldStyle,
    FTextFieldStyleDelta>.delta([
      .all(FTextFieldStyleDelta.delta(
        
    keyboardAppearance: .light,
    // Input body color 
    color: .delta([.all(colors.secondaryForeground.withValues(alpha: 0.3))]), 
    iconStyle: .delta([.all(.delta(color: colors.primaryForeground))]), 
    clearButtonStyle: .delta(
      contentStyle: .delta(
        textStyle: .delta([.all(.delta())]),
        iconStyle: .delta([.all(.delta())]),
        circularProgressStyle: .delta([.all(.delta(iconStyle: .delta()))]),
      ),
      iconContentStyle: .delta(iconStyle: .delta([])),
      tappableStyle: .delta(),
      focusedOutlineStyle: .delta(color: colors.background, borderRadius: .zero)
      ),

      obscureButtonStyle: .delta(
        decoration: .delta([]),
        contentStyle: .delta(
          textStyle: .delta([]),
          iconStyle: .delta([.all(.delta())]),
          circularProgressStyle: .delta([])
        ),
        iconContentStyle: .delta(iconStyle: .delta([])),
        tappableStyle: .delta(),
        focusedOutlineStyle: .delta(color: colors.background, borderRadius: .zero)
      ),
      
      contentTextStyle: .delta([.all(.delta(color: colors.background))]),
      hintTextStyle: .delta([.all(.delta(color: colors.background))]),
      counterTextStyle: .delta([.all(.delta())]),
      border: .delta([.all(.none)]),
      labelTextStyle: .delta([.all(.delta(color: colors.primaryForeground))]),
      descriptionTextStyle: .delta([.all(.delta(color: colors.primaryForeground))]),
      errorTextStyle: .delta([.all(.delta())]),

      ))
    ])
);
