import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// extension CustomFDividerStyles on Never {
///   // Modify this function's body.
///   static FDividerStyles dividerStyles({
///     required FColorScheme color,
///     required FStyle style,
///   }) => FDividerStyles(
///     horizontalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.horizontalStyle,
///       width: style.borderWidth,
///     ),
///     verticalStyle: FDividerStyle(
///       colors: colors.secondary,
///       padding: FDividerStyle.defaultPadding.verticalStyle,
///       width: style.borderWidth,
///     ),
///   );
/// }
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.color,
///  style: FThemes.neutral.light.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.color,
///    style: FThemes.neutral.light.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
extension CustomFFormFieldStyle on Never {
  static FFormFieldStyle formFieldStyle({
    required FColors colors,
    required FTypography typography,
  }) => FFormFieldStyle(
    labelTextStyle: FVariants.from(
      typography.body.xs.copyWith(color: Colors.grey[400], fontWeight: .normal),
      variants: {
        [.error]: .delta(color: colors.error),
        [.disabled]: .delta(color: colors.disable(colors.foreground)),
        [.disabled.and(.error)]: .delta(color: colors.disable(colors.error)),
      },
    ),
    descriptionTextStyle: FVariants.from(
      typography.body.sm.copyWith(color: colors.mutedForeground),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
      },
    ),
    errorTextStyle: FVariants.from(
      typography.body.sm.copyWith(color: colors.error, fontWeight: .w600),
      variants: {
        [.disabled]: .delta(color: colors.disable(colors.error)),
      },
    ),
  );
}
