
import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
//
// Modify the generated function bodies to create your own custom style.
// Then, call the modified functions and pass the results to your FThemeData.
//
// ### Example
// Generated style:
// ```dart
// // Modify this function's body.
// FDividerStyles dividerStyles({
//   required FColorScheme color,
//   required FStyle style,
// }) => FDividerStyles(
//   horizontalStyle: FDividerStyle(
//     colors: colors.secondary,
//     padding: FDividerStyle.defaultPadding.horizontalStyle,
//     width: style.borderWidth,
//   ),
//   verticalStyle: FDividerStyle(
//     colors: colors.secondary,
//     padding: FDividerStyle.defaultPadding.verticalStyle,
//     width: style.borderWidth,
//   ),
// );
// ```
//
// File that contains your `FThemeData`:
// ```dart
// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
//
// FThemeData(
//  color: FThemes.neutral.light.color,
//  style: FThemes.neutral.light.style,
//  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
//    color: FThemes.neutral.light.color,
//    style: FThemes.neutral.light.style,
//   ),
// );
// ```
//
// A theme can be generated using the Forui CLI:
// ```shell
// dart forui theme create [theme name]
// ```
//
// See https://forui.dev/docs/guides/customizing-themes for more information.
FSelectStyle selectStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) =>
    FSelectStyle(
      fieldStyle: .inherit(
        colors: colors,
        typography: typography,
        style: style,
      ),
      searchStyle: .inherit(
        colors: colors,
        typography: typography,
        style: style,
      ),
      contentStyle: .inherit(
        colors: colors,
        typography: typography,
        style: style,
      ),
      emptyTextStyle: typography.sm,
    ).copyWith(
      emptyTextStyle: TextStyleDelta.delta(
        color: colors.error,
        backgroundColor: colors.error,
      ),
    
      fieldStyle: FTextFieldStyleDelta.delta(

        //DISPLAY HINT TEXT
        hintTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.primaryForeground
            ),
            [FTextFieldVariantConstraint.not(.linux)]: TextStyle(
              color: colors.primaryForeground
            )
          }
        ),
        // SELECT DISPLAY TEXT
        contentTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.primaryForeground
            ),
            [FTextFieldVariantConstraint.not(.linux)]: TextStyle(
              color: colors.primaryForeground
            )
          }
        ),

        // counterTextStyle: FVariants(
        //   const TextStyle(),
        //   variants: {
        //     []: TextStyle(
        //       color: colors.destructive
        //     ),
        //     [FTextFieldVariantConstraint.not(.linux)]: TextStyle(
        //       color: colors.destructive
        //     )
        //   }
        // ),

        errorTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.destructive
            ),
            [FFormFieldErrorVariantConstraint.not(.linux)]: TextStyle(
              color: colors.destructive
            )
          }
        ),

        labelTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.primaryForeground
            ),
            [FFormFieldVariantConstraint.not(.linux)]: TextStyle(
              color: colors.primaryForeground
            )
          }
        ),

        descriptionTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.error
            ),
            [FFormFieldVariantConstraint.not(.linux)]: TextStyle(
              color: colors.error
            )
          }
        ),
        
        color: FVariants(
          colors.secondaryForeground,
           variants: {
            []: colors.secondaryForeground
           }
        ),
      ),

      contentStyle: FSelectContentStyleDelta.delta(
        scrollHandleStyle: FSelectScrollHandleStyleDelta.delta(
          background: Colors.blueAccent,
        ),
        viewInsets: EdgeInsets.all(10),
        decoration: BoxDecorationDelta.delta(
          color: colors.secondaryForeground,
          
        ),

        
        sectionStyle: FSelectSectionStyleDelta.delta(


          labelTextStyle: FVariants(
            const TextStyle(), 
            variants: {
              [FSelectSectionVariantConstraint.not(.linux)]: TextStyle(
                color: colors.secondary
              )
            }),
          itemStyle: FItemStyleDelta.delta(
            rawItemContentStyle: FRawItemContentStyleDelta.delta(
              childTextStyle: FVariants(
                const TextStyle(),
                variants: {
                  []: TextStyle(
                    color: colors.secondary
                  ),
                  [FTappableVariantConstraint.not(.linux)]: TextStyle(
                    color: colors.secondary
                  )
                }
              ) 
            ),
            
            // Drop down menu background
            decoration: FVariants(

              const BoxDecoration(),
              variants: {
                [FTappableVariantConstraint.touch]: BoxDecoration(
                  color: colors.primaryForeground,
                ),
                [FTappableVariantConstraint.hovered]: BoxDecoration(
                  color: colors.primaryForeground,
                  
                ),
                [FTappableVariantConstraint.focused]: BoxDecoration(
                  color: colors.primaryForeground,
                  
                ),
              },
            ),
            
            tappableStyle: FTappableStyleDelta.delta(

            ),
            contentStyle: FItemContentStyleDelta.delta(
              titleTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.secondaryForeground
            ),
            [FTappableVariantConstraint.focused]: TextStyle(
              color: colors.secondaryForeground
            )
          }
        )
            ),
          ),
        ),
      ),
    );
