
import 'package:flutter/material.dart';
import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FSelectStyle selectStyle({
  required FColors colors,
  required FIcons icons,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) => FSelectStyle(
  fieldStyles: .inherit(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ),
  searchStyle: .inherit(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ),
  contentStyle: .inherit(
    colors: colors,
    icons: icons,
    typography: typography,
    style: style,
    touch: touch,
  ),
  emptyTextStyle: typography.body.sm,
).copyWith(
    emptyTextStyle: TextStyleDelta.delta(
        color: colors.error,
        backgroundColor: colors.error,
      ),
      
    
  fieldStyles: FVariantsDelta<
    FTextFieldSizeVariantConstraint,
    FTextFieldSizeVariant,
    FTextFieldStyle,
    FTextFieldStyleDelta>.delta([
      .all(
          FTextFieldStyleDelta.delta(
            // display hint text
            hintTextStyle: FVariantsDelta.delta(
              [FVariantOperation.all(
    TextStyleDelta.delta(
      color: colors.primaryForeground,
    ),
  ),]),
            // selected input text color
            contentTextStyle: FVariants(
              const TextStyle(),
              variants: {
                [FTextFieldVariantConstraint.not(.linux)]: TextStyle(
                  color: colors.primaryForeground
                )
              }
            ),
            
            counterTextStyle: FVariants(
              const TextStyle(),
              variants: {
                []: TextStyle(
                  color: colors.destructive
                ),
                [FTextFieldVariantConstraint.not(.linux)]: TextStyle(
                  color: colors.destructive
                )
              }
            ),

            errorTextStyle: FVariants(
              const TextStyle(),
              variants: {
                []: TextStyle(
                  color: colors.destructive
                ),
                [FFormFieldErrorVariantConstraint.not(.linux)]: TextStyle(
                  color: colors.destructive
                )
              }
            ),

            labelTextStyle: FVariants(
                const TextStyle(),
                variants: {
                  []: TextStyle(
                    color: colors.primaryForeground
                  ),
                  [FFormFieldVariantConstraint.not(.linux)]: TextStyle(
                    color: colors.primaryForeground
                  )
                }
              ),

            descriptionTextStyle: FVariants(
              const TextStyle(),
              variants: {
                []: TextStyle(
                  color: colors.error
                ),
                [FFormFieldVariantConstraint.not(.linux)]: TextStyle(
                  color: colors.error
                )
              }
            ),

            color: FVariants(
              colors.secondaryForeground,
                variants: {
                []: colors.secondaryForeground
                }
            ),
          ),
      ),
]),

  contentStyle: .delta(
      
      scrollHandleStyle: .delta(
        background: Colors.blueAccent
      ),

      decoration: .boxDelta(
        color: colors.secondaryForeground
      ),

      sectionStyle: .delta(
        
        labelTextStyle: FVariants(
          const TextStyle(), variants: {
            [FSelectSectionVariantConstraint.not(.linux)]: TextStyle(
              color: colors.secondary,
            )
          }),
        itemStyle: .delta(
          rawContentStyle: .delta(
            childTextStyle: FVariants(
              const TextStyle(),
              variants: {
                []: TextStyle(color: colors.destructive),
                [FTappableVariantConstraint.not(.linux)]: TextStyle(
                  color: colors.destructive
                ),
                
              })
          ),
          contentStyle: FItemContentStyleDelta.delta(
              titleTextStyle: FVariants(
          const TextStyle(),
          variants: {
            []: TextStyle(
              color: colors.primaryForeground
            ),
            [FTappableVariantConstraint.focused]: TextStyle(
              color: colors.primaryForeground
            )
          }
        )
            ),
        ),

        
      )
      
    ),
    

);
