import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FTextFieldSizeStyles textFieldSizeStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final iconStyle =
      FVariants<
        FTextFieldVariantConstraint,
        FTextFieldVariant,
        IconThemeData,
        IconThemeDataDelta
      >.from(
        IconThemeData(
          color: colors.mutedForeground,
          size: typography.body.sm.fontSize,
        ),
        variants: {
          [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
        },
      );
  FTextFieldStyle textField(
    FButtonStyle buttonStyle,
    BoxConstraints constraints,
    EdgeInsetsGeometry contentPadding,
  ) => _textFieldStyle(
    colors: colors,
    style: style,
    labelStyle: _labelStyles(style: style).verticalStyle,
    textStyle: typography.body.sm,
    iconStyle: iconStyle,
    buttonStyle: buttonStyle,
    constraints: constraints,
    contentPadding: contentPadding,
  );
  final ghost = _buttonStyles(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ).ghost;
  final buttonStyle = ghost.sm.copyWith(
    iconContentStyle: ghost.sm.iconContentStyle.copyWith(
      iconStyle: iconStyle.cast(),
    ),
  );
  if (touch) {
    final md = textField(
      buttonStyle,
      const BoxConstraints(minHeight: 44),
      const .symmetric(horizontal: 12, vertical: 10),
    );
    return FTextFieldSizeStyles(
      FVariants(
        md,
        variants: {
          [.sm]: textField(
            buttonStyle,
            const BoxConstraints(minHeight: 40),
            const .symmetric(horizontal: 12, vertical: 8),
          ),
          [.md]: md,
          [.lg]: textField(
            buttonStyle,
            const BoxConstraints(minHeight: 48),
            const .symmetric(horizontal: 12, vertical: 12),
          ),
        },
      ),
    );
  } else {
    final md = textField(
      buttonStyle,
      const BoxConstraints(minHeight: 36),
      const .symmetric(horizontal: 10, vertical: 9),
    );
    return FTextFieldSizeStyles(
      FVariants(
        md,
        variants: {
          [.sm]: textField(
            ghost.xs.copyWith(
              iconContentStyle: ghost.xs.iconContentStyle.copyWith(
                iconStyle: iconStyle.cast(),
              ),
            ),
            const BoxConstraints(minHeight: 32),
            const .symmetric(horizontal: 10, vertical: 7),
          ),
          [.md]: md,
          [.lg]: textField(
            buttonStyle,
            const BoxConstraints(minHeight: 40),
            const .symmetric(horizontal: 10, vertical: 11),
          ),
        },
      ),
    );
  }
}

FTextFieldStyle _textFieldStyle({
  required FColors colors,
  required FStyle style,
  required FLabelStyle labelStyle,
  required TextStyle textStyle,
  required FVariants<
    FTextFieldVariantConstraint,
    FTextFieldVariant,
    IconThemeData,
    IconThemeDataDelta
  >
  iconStyle,
  required FButtonStyle buttonStyle,
  required BoxConstraints constraints,
  required EdgeInsetsGeometry contentPadding,
}) => FTextFieldStyle(
  keyboardAppearance: colors.brightness,
  color: FVariants(
    colors.card,
    variants: {
      [.disabled]: colors.disable(colors.card),
    },
  ),
  cursorColor: colors.primaryForeground,
  constraints: constraints,
  contentPadding: contentPadding,
  iconStyle: iconStyle,
  clearButtonStyle: buttonStyle,
  obscureButtonStyle: buttonStyle.copyWith(
    tappableStyle: const .delta(
      motion: .delta(bounceTween: FTappableMotion.noBounceTween),
    ),
  ),
  contentTextStyle: FVariants.from(
    textStyle.copyWith(color: colors.foreground),
    variants: {
      [.disabled]: .delta(color: colors.disable(colors.foreground)),
    },
  ),
  hintTextStyle: FVariants.from(
    textStyle.copyWith(color: colors.mutedForeground),
    variants: {
      [.disabled]: .delta(color: colors.disable(colors.mutedForeground)),
    },
  ),
  counterTextStyle: FVariants.from(
    textStyle.copyWith(color: colors.foreground),
    variants: {
      [.disabled]: .delta(color: colors.disable(colors.foreground)),
    },
  ),
  border: FVariants(
    OutlineInputBorder(
      borderSide: BorderSide(color: colors.border, width: style.borderWidth),
      borderRadius: style.borderRadius.md,
    ),
    variants: {
      [.focused]: OutlineInputBorder(
        borderSide: BorderSide(color: colors.primary, width: style.borderWidth),
        borderRadius: style.borderRadius.md,
      ),
      [.disabled]: OutlineInputBorder(
        borderSide: BorderSide(
          color: colors.disable(colors.border),
          width: style.borderWidth,
        ),
        borderRadius: style.borderRadius.md,
      ),
      [.error]: OutlineInputBorder(
        borderSide: BorderSide(color: colors.error, width: style.borderWidth),
        borderRadius: style.borderRadius.md,
      ),
      [.error.and(.disabled)]: OutlineInputBorder(
        borderSide: BorderSide(
          color: colors.disable(colors.error),
          width: style.borderWidth,
        ),
        borderRadius: style.borderRadius.md,
      ),
    },
  ),
  labelTextStyle: style.formFieldStyle.labelTextStyle,
  descriptionTextStyle: style.formFieldStyle.descriptionTextStyle,
  errorTextStyle: style.formFieldStyle.errorTextStyle,
  labelPadding: labelStyle.labelPadding,
  descriptionPadding: labelStyle.descriptionPadding,
  errorPadding: labelStyle.errorPadding,
  childPadding: labelStyle.childPadding,
  cursorWidth: 2.0,
  clearButtonPadding: const .directional(end: 4),
  obscureButtonPadding: const .directional(end: 4),
  scrollPadding: const .all(20),
  labelMotion: const FLabelMotion(),
);

FLabelStyles _labelStyles({required FStyle style}) => FLabelStyles(
  horizontalLeadingStyle: .inherit(
    style: style,
    descriptionPadding: const .only(top: 2),
    errorPadding: const .only(top: 2),
    childPadding: const .symmetric(horizontal: 12),
  ),
  horizontalTrailingStyle: .inherit(
    style: style,
    descriptionPadding: const .only(top: 2),
    errorPadding: const .only(top: 2),
    childPadding: const .symmetric(horizontal: 8),
  ),
  verticalStyle: .inherit(
    style: style,
    labelPadding: const .only(bottom: 6),
    descriptionPadding: const .only(top: 6),
    errorPadding: const .only(top: 6),
  ),
);

FButtonStyles _buttonStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primary = _buttonSizeStyles(
    typography: typography,
    style: style,
    touch: touch,
    decoration: (radius) => .from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(borderRadius: radius),
        color: colors.primary,
      ),
      variants: {
        [.hovered, .pressed]: .shapeDelta(color: colors.hover(colors.primary)),
        [.disabled]: .shapeDelta(color: colors.disable(colors.primary)),
        [.selected]: .shapeDelta(color: colors.hover(colors.primary)),
        [.selected.and(.disabled)]: .shapeDelta(
          color: colors.disable(colors.hover(colors.primary)),
        ),
      },
    ),
    foregroundColor: colors.primaryForeground,
    disabledForegroundColor: colors.disable(colors.primaryForeground),
  );
  return FButtonStyles(
    FVariants(
      primary,
      variants: {
        [.primary]: primary,
        [.secondary]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.primaryForeground,
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(
                color: colors.hover(colors.primaryForeground),
              ),
              [.disabled]: .shapeDelta(color: colors.disable(colors.primaryForeground)),
              [.selected]: .shapeDelta(color: colors.hover(colors.primaryForeground)),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.hover(colors.primaryForeground)),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.destructive]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.destructive.withValues(
                alpha: colors.brightness == .light ? 0.1 : 0.2,
              ),
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.disabled]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.05 : 0.1,
                ),
              ),
              [.selected]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(
                  colors.destructive.withValues(
                    alpha: colors.brightness == .light ? 0.2 : 0.3,
                  ),
                ),
              ),
            },
          ),
          foregroundColor: colors.destructive,
          disabledForegroundColor: colors.destructive.withValues(alpha: 0.5),
        ),
        [.outline]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(
                side: BorderSide(
                  color: colors.border,
                  width: style.borderWidth,
                ),
                borderRadius: radius,
              ),
              color: colors.card,
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(color: colors.primaryForeground),
              [.disabled]: .shapeDelta(color: colors.disable(colors.card)),
              [.selected]: .shapeDelta(color: colors.primaryForeground),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.primaryForeground),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.ghost]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
            ),
            variants: {
              [.hovered, .pressed]: .shapeDelta(color: colors.primaryForeground),
              [.disabled]: const .shapeDelta(),
              [.selected]: .shapeDelta(color: colors.primaryForeground),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.primaryForeground),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
      },
    ),
  );
}

FButtonSizeStyles _buttonSizeStyles({
  required FTypography typography,
  required FStyle style,
  required FVariants<
    FTappableVariantConstraint,
    FTappableVariant,
    Decoration,
    DecorationDelta
  >
  Function(BorderRadiusGeometry radius)
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
  required bool touch,
}) {
  if (touch) {
    final md = _buttonStyle(
      style: style,
      foregroundColor: foregroundColor,
      disabledForegroundColor: disabledForegroundColor,
      decoration: decoration(style.borderRadius.md),
      textStyle: typography.body.sm,
      contentConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      contentPadding: const .symmetric(horizontal: 12, vertical: 14),
      contentSpacing: 6,
      iconConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      iconSize: typography.body.md.fontSize ?? 18,
      iconPadding: const .all(13),
    );
    return FButtonSizeStyles(
      FVariants(
        md,
        variants: {
          [.xs]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.sm),
            textStyle: typography.body.xs,
            contentConstraints: const BoxConstraints(
              minWidth: 32,
              minHeight: 32,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 9),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            iconSize: typography.body.sm.fontSize ?? 16,
            iconPadding: const .all(8),
          ),
          [.sm]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 40,
              minHeight: 40,
            ),
            contentPadding: const .symmetric(horizontal: 12, vertical: 12),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
            iconSize: typography.body.md.fontSize ?? 18,
            iconPadding: const .all(11),
          ),
          [.md]: md,
          [.lg]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 48,
              minHeight: 48,
            ),
            contentPadding: const .symmetric(horizontal: 12, vertical: 16),
            contentSpacing: 6,
            iconConstraints: const BoxConstraints(minWidth: 48, minHeight: 48),
            iconSize: typography.body.lg.fontSize ?? 20,
            iconPadding: const .all(14),
          ),
        },
      ),
    );
  } else {
    final md = _buttonStyle(
      style: style,
      foregroundColor: foregroundColor,
      disabledForegroundColor: disabledForegroundColor,
      decoration: decoration(style.borderRadius.md),
      textStyle: typography.body.sm,
      contentConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
      contentPadding: const .symmetric(horizontal: 10, vertical: 11),
      contentSpacing: 6,
      iconConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
      iconSize: typography.body.md.fontSize ?? 16,
      iconPadding: const .all(10),
    );
    return FButtonSizeStyles(
      FVariants(
        md,
        variants: {
          [.xs]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.sm),
            textStyle: typography.body.xs,
            contentConstraints: const BoxConstraints(
              minWidth: 24,
              minHeight: 24,
            ),
            contentPadding: const .symmetric(horizontal: 8, vertical: 6),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 24, minHeight: 24),
            iconSize: typography.body.sm.fontSize ?? 14,
            iconPadding: const .all(5),
          ),
          [.sm]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 32,
              minHeight: 32,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 9),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            iconSize: typography.body.md.fontSize ?? 16,
            iconPadding: const .all(8),
          ),
          [.md]: md,
          [.lg]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 40,
              minHeight: 40,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 13),
            contentSpacing: 6,
            iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
            iconSize: typography.body.lg.fontSize ?? 18,
            iconPadding: const .all(11),
          ),
        },
      ),
    );
  }
}

FButtonStyle _buttonStyle({
  required FStyle style,
  required FVariants<
    FTappableVariantConstraint,
    FTappableVariant,
    Decoration,
    DecorationDelta
  >
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
  required TextStyle textStyle,
  required BoxConstraints contentConstraints,
  required EdgeInsetsGeometry contentPadding,
  required double contentSpacing,
  required BoxConstraints iconConstraints,
  required double iconSize,
  required EdgeInsetsGeometry iconPadding,
}) => FButtonStyle(
  decoration: decoration,
  focusedOutlineStyle: style.focusedOutlineStyle,
  contentStyle: FButtonContentStyle(
    textStyle: .from(
      textStyle.copyWith(color: foregroundColor, fontWeight: .w500, height: 1),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    iconStyle: .from(
      IconThemeData(color: foregroundColor, size: textStyle.fontSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    circularProgressStyle: .from(
      FCircularProgressStyle(
        iconStyle: IconThemeData(
          color: foregroundColor,
          size: textStyle.fontSize,
        ),
      ),
      variants: {
        [.disabled]: .delta(iconStyle: .delta(color: disabledForegroundColor)),
      },
    ),
    padding: contentPadding,
    spacing: contentSpacing,
    constraints: contentConstraints,
  ),
  iconContentStyle: FButtonIconContentStyle(
    iconStyle: .from(
      IconThemeData(color: foregroundColor, size: iconSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    padding: iconPadding,
    constraints: iconConstraints,
  ),
  tappableStyle: style.tappableStyle,
);
