import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:spine/theme/alert_styles.dart';
import 'package:spine/theme/badge_styles.dart';
import 'package:spine/theme/card_style.dart';
import 'package:spine/theme/circular_progress_style.dart';
import 'package:spine/theme/date_field_style.dart';
import 'package:spine/theme/form_field_style.dart';
import 'package:spine/theme/select_style.dart';
import 'package:spine/theme/switch_style.dart';
import 'package:spine/theme/text_field_style.dart';
import 'package:spine/theme/toaster_style.dart';


// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get greenDark {
  const colors = FColors(
    brightness: .dark,
    systemOverlayStyle: .light,
    barrier: Color.fromARGB(255, 109, 40, 217),
    background: Color(0xFF09090B),
    foreground: Color.fromARGB(255, 23, 26, 33),
    primary: Color.fromARGB(255, 16, 185, 129),
    primaryForeground: Color.fromARGB(255, 255, 255, 255),
    secondary: Color.fromARGB(255, 7, 133, 236),
    secondaryForeground: Color.fromARGB(255, 24, 32, 46),
    muted: Color(0xFF27272A),
    mutedForeground: Color(0xFFA1A1AA),
    destructive: Color.fromARGB(255, 242, 92 , 77),
    destructiveForeground: Color(0xFFFAFAFA),
    error: Color(0xFF7F1D1D),
    errorForeground: Color(0xFFFAFAFA),
    border: Color(0xFF27272A),
    card: Color.fromARGB(255, 24, 32, 46),
    
  );

  final typography = _typography(colors: colors, defaultFontFamily: GoogleFonts.manrope().fontFamily!);
  final style = _style(colors: colors, typography: typography);

  return FThemeData(
    colors: colors, 
    typography: typography, 
    style: style,

    dateFieldStyle: dateFieldStyle(colors: colors, typography: typography, style: style),
    switchStyle: switchStyle(colors: colors, style: style),
    circularProgressStyle: circularProgressStyle(colors: colors),
    toasterStyle: toasterStyle(colors: colors, typography: typography, style: style),
    alertStyles: alertStyles(colors: colors, typography: typography, style: style),
    textFieldStyle: textFieldStyle(colors: colors, typography: typography, style: style),
    selectStyle: selectStyle(colors: colors, typography: typography, style: style),
    cardStyle: cardStyle(colors: colors, typography: typography, style: style),
    badgeStyles: badgeStyles(colors: colors, typography: typography, style: style),
  );
}


FTypography _typography({
  required FColors colors,
  required final String defaultFontFamily,
}) => FTypography(
  xs: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 12,
    height: 1,
    
  ),
  sm: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 14,
    height: 1,
  ),
  base: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 16,
    height: 1,
  ),
  lg: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 18,
    height: 1,
  ),
  xl: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 20,
    height: 1,
  ),
  xl2: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 22,
    height: 1,
  ),
  xl3: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 30,
    height: 1,
  ),
  xl4: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 36,
    height: 1,
  ),
  xl5: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 48,
    height: 1,
  ),
  xl6: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 60,
    height: 1,
  ),
  xl7: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 72,
    height: 1,
  ),
  xl8: TextStyle(
    color: colors.primaryForeground,
    fontFamily: defaultFontFamily,
    fontSize: 96,
    height: 1,
  ),
);

FStyle _style({required FColors colors, required FTypography typography}) =>
    FStyle(
      formFieldStyle: CustomFFormFieldStyle.formFieldStyle(colors: colors, typography: typography),
      focusedOutlineStyle: FFocusedOutlineStyle(
        color: colors.primary,
        borderRadius: const .all(.circular(8)),
      ),
      iconStyle: IconThemeData(color: colors.foreground, size: 20),
      tappableStyle: FTappableStyle(),
      borderRadius: const FLerpBorderRadius.all(.circular(8), min: 24),
      borderWidth: 1,
      pagePadding: const .symmetric(vertical: 8, horizontal: 12),
      shadow: const [
        BoxShadow(
          color: Color(0x0d000000),
          offset: Offset(0, 1),
          blurRadius: 2,
        ),
      ],
    );
