import 'package:forui/forui.dart';
import 'package:flutter/material.dart';
import 'package:spine/theme/alert_styles-new.dart';
import 'package:spine/theme/badge_styles.dart';
import 'package:spine/theme/card_style.dart';
import 'package:spine/theme/circular_progress_size_styles.dart';
import 'package:spine/theme/date_field_style.dart';
import 'package:spine/theme/select_style.dart';
import 'package:spine/theme/switch_style.dart';
import 'package:spine/theme/text_field_size_styles.dart';
import 'package:spine/theme/toaster_style.dart';

part 'colors.dart';
part 'typography.dart';
part 'style.dart';

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get greenLight {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = lightColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = FIcons(
    arrowLeft: FIcons.iconData(FLucideIcons.arrowLeft),
    calendar: FIcons.iconData(FLucideIcons.calendar),
    check: FIcons.iconData(FLucideIcons.check),
    chevronDown: FIcons.iconData(FLucideIcons.chevronDown),
    chevronLeft: FIcons.iconData(FLucideIcons.chevronLeft),
    chevronRight: FIcons.iconData(FLucideIcons.chevronRight),
    chevronUp: FIcons.iconData(FLucideIcons.chevronUp),
    chevronsUpDown: FIcons.iconData(FLucideIcons.chevronsUpDown),
    circleAlert: FIcons.iconData(FLucideIcons.circleAlert),
    clock4: FIcons.iconData(FLucideIcons.clock4),
    ellipsis: FIcons.iconData(FLucideIcons.ellipsis),
    eye: FIcons.iconData(FLucideIcons.eye),
    eyeClosed: FIcons.iconData(FLucideIcons.eyeClosed),
    gripHorizontal: FIcons.iconData(FLucideIcons.gripHorizontal),
    gripVertical: FIcons.iconData(FLucideIcons.gripVertical),
    loader: FIcons.iconData(FLucideIcons.loader),
    loaderCircle: FIcons.iconData(FLucideIcons.loaderCircle),
    loaderPinwheel: FIcons.iconData(FLucideIcons.loaderPinwheel),
    search: FIcons.iconData(FLucideIcons.search),
    userRound: FIcons.iconData(FLucideIcons.userRound),
    x: FIcons.iconData(FLucideIcons.x),
  );

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,

    dateFieldStyle: dateFieldStyle(touch: touch,icons: icons, hapticFeedback: .none(), colors: colors, typography: typography, style: style),
    switchStyle: switchStyle(colors: colors, style: style),
    circularProgressStyles: circularProgressSizeStyles(typography: typography, colors: colors),
    toasterStyle: toasterStyle( touch: touch, colors: colors, typography: typography, style: style),
    textFieldStyles: textFieldSizeStyles( touch: touch, colors: colors, typography: typography, style: style),
    selectStyle: selectStyle(touch: touch, icons: icons, colors: colors, typography: typography, style: style),
    cardStyle: cardStyle( touch: touch, colors: colors, typography: typography, style: style),
    badgeStyles: badgeStyles( touch: touch, colors: colors, typography: typography, style: style),
    alertStyles: alertStyles(touch: touch, colors: colors, typography: typography, style: style)
  );
}


FThemeData get greenDark {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = darkColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = FIcons(
    arrowLeft: FIcons.iconData(FLucideIcons.arrowLeft),
    calendar: FIcons.iconData(FLucideIcons.calendar),
    check: FIcons.iconData(FLucideIcons.check),
    chevronDown: FIcons.iconData(FLucideIcons.chevronDown),
    chevronLeft: FIcons.iconData(FLucideIcons.chevronLeft),
    chevronRight: FIcons.iconData(FLucideIcons.chevronRight),
    chevronUp: FIcons.iconData(FLucideIcons.chevronUp),
    chevronsUpDown: FIcons.iconData(FLucideIcons.chevronsUpDown),
    circleAlert: FIcons.iconData(FLucideIcons.circleAlert),
    clock4: FIcons.iconData(FLucideIcons.clock4),
    ellipsis: FIcons.iconData(FLucideIcons.ellipsis),
    eye: FIcons.iconData(FLucideIcons.eye),
    eyeClosed: FIcons.iconData(FLucideIcons.eyeClosed),
    gripHorizontal: FIcons.iconData(FLucideIcons.gripHorizontal),
    gripVertical: FIcons.iconData(FLucideIcons.gripVertical),
    loader: FIcons.iconData(FLucideIcons.loader),
    loaderCircle: FIcons.iconData(FLucideIcons.loaderCircle),
    loaderPinwheel: FIcons.iconData(FLucideIcons.loaderPinwheel),
    search: FIcons.iconData(FLucideIcons.search),
    userRound: FIcons.iconData(FLucideIcons.userRound),
    x: FIcons.iconData(FLucideIcons.x),
  );

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,

    dateFieldStyle: dateFieldStyle( touch: touch, icons: icons, hapticFeedback: .none(), colors: colors, typography: typography, style: style),
    switchStyle: switchStyle(colors: colors, style: style),
    circularProgressStyles: circularProgressSizeStyles(typography: typography, colors: colors),
    toasterStyle: toasterStyle( touch: touch, colors: colors, typography: typography, style: style),
    textFieldStyles: textFieldSizeStyles( touch: touch, colors: colors, typography: typography, style: style),
    selectStyle: selectStyle(touch: touch, icons: icons, colors: colors, typography: typography, style: style),
    cardStyle: cardStyle(touch: touch, colors: colors, typography: typography, style: style),
    badgeStyles: badgeStyles(touch: touch, colors: colors, typography: typography, style: style),
    alertStyles: alertStyles(colors: colors, typography: typography, style: style, touch: touch)
  );
}
